spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://127.0.0.1:13306/exam?useSSL=false&serverTimezone=Asia/Seoul
    username: #username
    password: #password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #client-id
            client-secret: #client-secret
            authorization-grant-type: authorization_code
            redirect-uri: #callback uri
            scope:
              - profile
              - email
          naver:
            client-id: #client-id
            client-secret: #client-secret
            authorization-grant-type: authorization_code
            redirect-uri: #callback uri
            scope:
              - profile
          kakao:
            client-id: #client-id
            client-secret: #client-secret
            authorization-grant-type: authorization_code
            redirect-uri: #callback uri
            scope:
              - profile
              - account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            unlink-uri: https://accounts.google.com/o/oauth2/revoke
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            unlink-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            unlink-uri: https://kapi.kakao.com/v1/user/unlink
      authorized-redirect-uris:
        - http://localhost:3000
jwt:
  secretKey: #jwt-secret-key
  signatureAlgorithm: HS256
  tokenExpired: 604800 #(sec) 7 days
